import type { CSSProperties } from "react";
import { PANEL_WIDTH } from "./constants";

/** Co-located styles for AgentPicker. */
export const s = {
  wrapper: { position: "relative", display: "inline-block" },
  panel: {
    position: "absolute",
    top: "calc(100% + 6px)",
    right: 0,
    width: PANEL_WIDTH,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 10,
    zIndex: 40,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    animation: "ddpop .12s ease",
  },
  heading: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    padding: "2px 4px 4px",
  },
  mergedWarning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    padding: "6px 4px",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  },
  agentRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "6px 4px",
    borderRadius: 6,
  },
  agentName: {
    fontSize: 13.5,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  agentEstimate: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
    fontVariantNumeric: "tabular-nums",
  },
  empty: {
    padding: "8px 4px",
    fontSize: 13,
    color: "var(--text-secondary)",
  },
  divider: { height: 1, background: "var(--border)", margin: "4px 0" },
  summary: {
    fontSize: 12,
    color: "var(--text-secondary)",
    padding: "2px 4px",
    fontVariantNumeric: "tabular-nums",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingTop: 2,
  },
  configureLink: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 4px",
    fontSize: 12.5,
    color: "var(--text-muted)",
    cursor: "pointer",
    background: "none",
    border: "none",
    textAlign: "left",
  },
} satisfies Record<string, CSSProperties>;
