#!/usr/bin/env bash
# Deterministic half of pr-self-review: cheap, objective checks that run before
# any model reads the diff. Prints collect-diff.sh's records, then one line per
# result:
#
#   CRITICAL <check> <location> — <message>   # blocks; see references/severity.md
#   MAJOR    <check> <location> — <message>
#   SIGNAL   <check> <location> — <message>   # grep hint; a reviewer must confirm it
#   DETAIL   <check> <location> — <message>   # tool output backing the CRITICAL after it
#   PASS     <check>
#   SKIP     <check> — <reason>
#   SUMMARY critical=<n> major=<n> signal=<n>
#
# No tests run here, by design: the self-review has to stay fast.
# Exit code: 1 when any CRITICAL was reported, 0 otherwise, 2 on setup failure.
#
# Usage: precheck.sh [base-branch]   (default: main)
# Written for the macOS bash 3.2: no associative arrays, no mapfile.
set -uo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
root="$(git rev-parse --show-toplevel)" || exit 2
cd "$root"

collected="$("$here/collect-diff.sh" "${1:-main}")" || exit 2
echo "$collected"

base="$(awk '/^BASE /{print $2}' <<<"$collected")"
files="$(grep '^FILE ' <<<"$collected" || true)"
paths="$(awk '{print $5}' <<<"$files")"

T=$'\t'
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

critical=0
major=0
signal=0
report() { # severity check location message
  case "$1" in
    CRITICAL) critical=$((critical + 1)) ;;
    MAJOR) major=$((major + 1)) ;;
    SIGNAL) signal=$((signal + 1)) ;;
  esac
  echo "$1 $2 $3 — $4"
}

if [ -z "$files" ]; then
  echo "SKIP all — no open changes against $base"
  echo "SUMMARY critical=0 major=0 signal=0"
  exit 0
fi

# --- 1. Do-not-touch paths ---------------------------------------------------
# Migrations are generated by drizzle-kit: NEW files (and the journal/snapshot
# updates that come with them) are expected next to a schema change. Editing or
# deleting an existing migration is the violation.
schema_changed=0
grep -qE '^server/src/db/schema' <<<"$paths" && schema_changed=1
dnt_before=$critical
while read -r _ _ kind status path _; do
  [ "$kind" = "protected" ] || continue
  case "$path" in
    server/src/db/migrations/meta/_journal.json | server/src/db/migrations/*)
      if [ "$status" = "A" ] || [ "$status" = "??" ] || [ "$path" = "server/src/db/migrations/meta/_journal.json" ]; then
        [ "$schema_changed" = 1 ] ||
          report MAJOR migration-without-schema "$path" "migration changed but no db/schema file did; was it generated by drizzle-kit (pnpm db:generate)?"
      else
        report CRITICAL do-not-touch "$path" "existing migration edited ($status); migrations are generated by drizzle-kit — add a new one instead"
      fi
      ;;
    *)
      report CRITICAL do-not-touch "$path" "generated or vendored path (root CLAUDE.md Do-not-touch); revert the edit"
      ;;
  esac
done <<<"$files"
[ "$critical" = "$dnt_before" ] && echo "PASS do-not-touch"

# --- Added lines of every reviewable file: path<TAB>line<TAB>content ----------
added="$tmp/added.tsv"
: >"$added"
while read -r _ _ kind status path old; do
  case "$kind" in protected | lockfile) continue ;; esac
  [ "$status" = "D" ] && continue
  [ -f "$path" ] || continue
  if [ "$status" = "??" ]; then
    awk -v p="$path" '{print p "\t" NR "\t" $0}' "$path"
  else
    git diff -M -U0 "$base" -- ${old:+"$old"} "$path" | awk -v p="$path" '
      /^@@/ { match($0, /\+[0-9]+/); n = substr($0, RSTART + 1, RLENGTH - 1); body = 1; next }
      !body { next }
      /^\+/ { print p "\t" n "\t" substr($0, 2); n++ }'
  fi >>"$added"
done <<<"$files"

# hits <path ERE> <content ERE> -> "path:line" per match, at most 10.
# Path EREs use [^\t]* instead of .* so they cannot run into the line field;
# POSIX brackets have no \t escape, so the literal "\t" is swapped for a tab here.
hits() {
  local path_re="${1//\\t/$T}"
  grep -E "^(${path_re})${T}[0-9]+${T}.*(${2})" "$added" 2>/dev/null |
    awk -F"$T" '{print $1 ":" $2}' | head -10
}

# --- 2. Secrets --------------------------------------------------------------
secret_re='sk-(proj-|or-v1-|ant-)?[A-Za-z0-9_-]{20,}|gh[pousr]_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{40,}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----|xox[baprs]-[A-Za-z0-9-]{10,}'
secret_hits="$(grep -E "^[^${T}]+${T}[0-9]+${T}.*(${secret_re})" "$added" 2>/dev/null |
  awk -F"$T" 'tolower($3) !~ /fake|dummy|example|placeholder|xxxx|mock|redacted|<your/ {print $1 ":" $2}' | head -10)"
env_files="$(grep -E '(^|/)\.env(\.[A-Za-z0-9_-]+)?$' <<<"$paths" | grep -Ev '\.env\.(example|sample|template)$' || true)"
if [ -n "$secret_hits" ]; then
  while IFS= read -r h; do
    report CRITICAL secret "$h" "credential-shaped value in the diff; remove it and rotate the key"
  done <<<"$secret_hits"
fi
if [ -n "$env_files" ]; then
  while IFS= read -r f; do
    report CRITICAL secret "$f" ".env file in the change set; secrets never go in git (root CLAUDE.md)"
  done <<<"$env_files"
fi
[ -z "$secret_hits$env_files" ] && echo "PASS secret"

# --- 3. Zod 4 through the v4 subpath ------------------------------------------
# zod 3.25 ships `zod/v4`, so Zod 4 API imported that way typechecks cleanly.
# Plain Zod 4 calls on the v3 `z` (z.email(), z.strictObject()) fail typecheck.
zod_hits="$(hits '[^\t]*\.(ts|tsx)' "['\"](zod/v4|zod/v4-mini|zod/mini|@zod/[a-z]+)['\"]")"
if [ -n "$zod_hits" ]; then
  while IFS= read -r h; do
    report CRITICAL zod-3-only "$h" "Zod 4 import; the repo is Zod 3 (root CLAUDE.md)"
  done <<<"$zod_hits"
else
  echo "PASS zod-3-only"
fi

# --- 4. Typecheck + arch:check, in parallel -----------------------------------
touched_pkg() {
  awk -v p="$1" '$2 == p && ($3 == "code" || $3 == "test" || $3 == "config") {f = 1} END {exit !f}' <<<"$files"
}

run_job() { # name dir cmd...
  local name="$1" dir="$2"
  shift 2
  (cd "$dir" && "$@") >"$tmp/$name.log" 2>&1
  echo $? >"$tmp/$name.rc"
}

jobs_started=""
start() { # name dir cmd...
  if [ ! -d "$2/node_modules" ]; then
    report CRITICAL "$1" "$2/" "cannot run: $2/node_modules is missing; install dependencies and rerun"
    return
  fi
  run_job "$@" &
  jobs_started="$jobs_started $1"
}

# server's tsconfig aliases @devdigest/reviewer-core to ../reviewer-core/src, so
# its typecheck also resolves reviewer-core's own deps (openai, zod) from there.
if touched_pkg server; then
  if [ -d server/node_modules ] && [ ! -d reviewer-core/node_modules ]; then
    report CRITICAL typecheck-server reviewer-core/ "cannot run: server typecheck compiles ../reviewer-core/src and needs reviewer-core/node_modules (cd reviewer-core && npm install)"
  else
    start typecheck-server server pnpm run typecheck
  fi
fi
touched_pkg client && start typecheck-client client pnpm run typecheck
touched_pkg reviewer-core && start typecheck-reviewer-core reviewer-core npm run --silent typecheck
touched_pkg e2e && start typecheck-e2e e2e npm run --silent typecheck
if grep -qE '^server/(src/|\.dependency-cruiser)' <<<"$paths"; then
  start arch-check server pnpm run arch:check
fi
wait

for name in typecheck-server typecheck-client typecheck-reviewer-core typecheck-e2e arch-check; do
  case " $jobs_started " in
    *" $name "*) ;;
    *) continue ;; # not touched (or already reported as not runnable)
  esac
  if [ "$(cat "$tmp/$name.rc")" = "0" ]; then
    echo "PASS $name"
    continue
  fi
  if [ "$name" = "arch-check" ]; then
    grep -E '^[[:space:]]*error ' "$tmp/$name.log" | head -10 | while IFS= read -r l; do
      echo "DETAIL arch-check server/ — ${l#"${l%%[![:space:]]*}"}"
    done
    report CRITICAL arch-check server/ "new layer violation; fix the import (onion-architecture §9), never re-baseline"
  else
    grep -E 'error TS[0-9]+' "$tmp/$name.log" | head -10 | while IFS= read -r l; do
      echo "DETAIL $name ${l%%:*} — ${l#*: }"
    done
    msg="typecheck failed; rerun the package's typecheck script for the full output"
    if [ "$name" = "typecheck-client" ] && grep -q '\.next/types' "$tmp/$name.log"; then
      msg="$msg — errors in .next/types after a moved route: rm -rf .next/types && pnpm exec next typegen (client/INSIGHTS.md)"
    fi
    report CRITICAL "$name" "${name#typecheck-}/" "$msg"
  fi
done
[ -z "$jobs_started" ] && echo "SKIP typecheck — no package code touched"

# --- 5. arch:check baseline must only shrink ----------------------------------
bl=server/.dependency-cruiser-known-violations.json
if grep -qxF "$bl" <<<"$paths"; then
  count() { node -e 'let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{try{console.log(JSON.parse(s).length)}catch{console.log(0)}})'; }
  before="$(git show "$base:$bl" 2>/dev/null | count)"
  after="$(count <"$bl")"
  if ! git cat-file -e "$base:$bl" 2>/dev/null; then
    report MAJOR arch-baseline "$bl" "baseline introduced with $after entries; confirm each is pre-existing debt of the rules added with it"
  elif [ "$after" -gt "$before" ] && grep -qxF server/.dependency-cruiser.cjs <<<"$paths"; then
    report MAJOR arch-baseline "$bl" "baseline grew $before -> $after together with a rule change; confirm the new entries are old code caught by the new rule, not new code"
  elif [ "$after" -gt "$before" ]; then
    report CRITICAL arch-baseline "$bl" "baseline grew $before -> $after; the baseline only shrinks (onion-architecture §9)"
  else
    echo "PASS arch-baseline ($before -> $after)"
  fi
fi

# --- 6. Coupled files -----------------------------------------------------------
# A change "touches" a symbol when the symbol appears within 10 lines of it.
# Hunk headers alone are not enough: for a class method git names the class
# (`@@ … export class ReviewRepository {`), not the method.
changed_sym() { # path symbol -> 0 when the diff of path touches symbol ('*' = any change)
  grep -qxF "$1" <<<"$paths" || return 1
  [ "$2" = "*" ] && return 0
  if [ -n "$(git ls-files --others --exclude-standard -- "$1")" ]; then
    grep -qF -- "$2" "$1"
  else
    git diff -U10 "$base" -- "$1" | grep -vE '^(\+\+\+|---) ' | grep -qF -- "$2"
  fi
}
major_before=$major
while read -r a sa b sb; do
  [ -z "${a:-}" ] && continue
  if changed_sym "$a" "$sa" && ! changed_sym "$b" "$sb"; then
    report MAJOR coupled-files "$a" "\`$sa\` changed but its twin \`$sb\` in $b did not (references/coupled-files.md)"
  elif changed_sym "$b" "$sb" && ! changed_sym "$a" "$sa"; then
    report MAJOR coupled-files "$b" "\`$sb\` changed but its twin \`$sa\` in $a did not (references/coupled-files.md)"
  fi
done < <(sed -nE 's/^- `([^`]+)` `([^`]+)` <-> `([^`]+)` `([^`]+)`.*/\1 \2 \3 \4/p' "$here/../references/coupled-files.md")

# The two vendor/shared copies: only the file that was touched is compared.
while IFS= read -r p; do
  case "$p" in
    server/src/vendor/shared/*) twin="client/src/vendor/shared/${p#server/src/vendor/shared/}" ;;
    client/src/vendor/shared/*) twin="server/src/vendor/shared/${p#client/src/vendor/shared/}" ;;
    *) continue ;;
  esac
  if [ -f "$twin" ] && ! grep -qxF "$twin" <<<"$paths"; then
    report MAJOR contract-copy "$p" "the other copy $twin was not changed; decide whether it needs the same edit (root INSIGHTS.md)"
  fi
done <<<"$paths"
[ "$major" = "$major_before" ] && echo "PASS coupled-files"

# --- 7. Grep signals for the reviewers (never blocking on their own) ----------
sig() { # check path-ERE content-ERE message
  local h
  h="$(hits "$2" "$3")"
  [ -z "$h" ] && return
  while IFS= read -r l; do report SIGNAL "$1" "$l" "$4"; done <<<"$h"
}
sig routes-query-db 'server/src/modules/[^/]+/routes\.ts' 'container\.db' \
  "route queries the DB; move it to the module's repository (onion-architecture §5)"
sig construct-in-service 'server/src/modules/[^\t]*(service|run-executor)\.ts' 'new [A-Z][A-Za-z]*(Repository|Adapter|Client)\(' \
  "service constructs its own dependency; take it through Deps (onion-architecture §5)"
sig process-env 'server/src/(modules|adapters)/[^\t]*\.ts' 'process\.env' \
  "env read below the composition root; go through platform/config.ts (onion-architecture §4)"
sig reply-outside-route 'server/src/modules/[^\t]*/(service|repository|helpers|run-executor|findings|status)[^\t]*\.ts' 'reply\.(code|status)\(' \
  "HTTP status set outside a route; throw an AppError subclass instead (onion-architecture §7)"
sig fetch-in-ui 'client/src/(app|components)/[^\t]*\.tsx?' '(^|[^A-Za-z.])fetch\(' \
  "direct fetch in UI; go through src/lib/hooks on src/lib/api.ts (client/CLAUDE.md)"
sig use-client-on-route 'client/src/app/[^\t]*(layout|page)\.tsx' "['\"]use client['\"]" \
  "'use client' on a route file; push it down to the interactive subtree (frontend-ui-architecture §8)"
sig hardcoded-string 'client/src/[^\t]*\.tsx' '>[[:space:]]*[A-Z][a-z]+( [a-z]+)+[[:space:]]*<' \
  "user-facing text outside next-intl (client/CLAUDE.md)"

# Several writes added to one server file that has no transaction.
multi="$(awk -F"$T" '$1 ~ /^server\/src\// && $3 ~ /\.(insert|update|delete)\(/ { n[$1]++; if (!($1 in first)) first[$1] = $2 }
  END { for (f in n) if (n[f] >= 2) print f ":" first[f] }' "$added")"
if [ -n "$multi" ]; then
  while IFS= read -r l; do
    grep -q 'transaction(' "${l%%:*}" ||
      report SIGNAL multi-write-no-tx "$l" "several writes added and no transaction in the file (onion-architecture §6)"
  done <<<"$multi"
fi

echo "SUMMARY critical=$critical major=$major signal=$signal"
[ "$critical" -eq 0 ]
