import type { CSSProperties } from "react";

/** Co-located styles for SkillsTab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  filter: { marginBottom: 10 } satisfies CSSProperties,
  hint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginBottom: 14,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  list: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  handle: {
    display: "flex",
    alignItems: "center",
    color: "var(--text-muted)",
    cursor: "grab",
  } satisfies CSSProperties,
  name: { fontSize: 14, color: "var(--text-primary)", flex: 1 } satisfies CSSProperties,
  nameOff: {
    fontSize: 14,
    color: "var(--text-muted)",
    textDecoration: "line-through",
    flex: 1,
  } satisfies CSSProperties,
  reorder: { display: "flex", alignItems: "center", gap: 2 } satisfies CSSProperties,
  reorderBtn: {
    display: "grid",
    placeItems: "center",
    width: 24,
    height: 24,
    padding: 0,
    borderRadius: 5,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-secondary)",
    cursor: "pointer",
  } satisfies CSSProperties,
  reorderBtnDisabled: {
    display: "grid",
    placeItems: "center",
    width: 24,
    height: 24,
    padding: 0,
    borderRadius: 5,
    border: "1px solid transparent",
    background: "transparent",
    color: "var(--text-muted)",
    opacity: 0.4,
    cursor: "default",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "16px 0" } satisfies CSSProperties,
} as const;
