import type { CSSProperties } from "react";
import { POPOVER_WIDTH } from "./constants";

/** Co-located styles for the finding-severity components. */
export const s = {
  counts: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
  } satisfies CSSProperties,
  count: (color: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 12.5,
    fontWeight: 600,
    color,
    borderBottom: `1px dotted ${color}`,
    paddingBottom: 1,
    lineHeight: 1.2,
  }),
  dash: { color: "var(--text-muted)" } satisfies CSSProperties,
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    cursor: "default",
    outline: "none",
  } satisfies CSSProperties,
  panel: (top: number, left: number, maxHeight: number): CSSProperties => ({
    position: "fixed",
    top,
    left,
    width: POPOVER_WIDTH,
    maxHeight,
    overflowY: "auto",
    overscrollBehavior: "contain",
    zIndex: 1000,
    padding: "12px 14px",
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    boxShadow: "0 12px 32px rgba(0,0,0,.45)",
    cursor: "default",
    textAlign: "left",
  }),
  header: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 4,
  } satisfies CSSProperties,
  muted: { fontSize: 12.5, color: "var(--text-muted)", padding: "8px 0" } satisfies CSSProperties,
  preview: (first: boolean): CSSProperties => ({
    display: "flex",
    flexDirection: "column",
    gap: 5,
    padding: "10px 0",
    borderTop: first ? "none" : "1px solid var(--border)",
  }),
  previewTitleRow: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
  } satisfies CSSProperties,
  previewBadge: { flexShrink: 0 } satisfies CSSProperties,
  previewTitle: {
    flex: 1,
    minWidth: 0,
    fontSize: 13.5,
    fontWeight: 600,
    lineHeight: 1.4,
    color: "var(--text-primary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  previewCategory: {
    display: "inline-flex",
    marginLeft: 8,
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  previewMeta: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
  } satisfies CSSProperties,
  previewFile: {
    flex: "0 1 auto",
    minWidth: 0,
    fontSize: 12,
    color: "var(--accent-text)",
    wordBreak: "break-all",
  } satisfies CSSProperties,
  previewNoWrap: { whiteSpace: "nowrap", flexShrink: 0 } satisfies CSSProperties,
  previewRationale: {
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  } satisfies CSSProperties,
} as const;
