import type { CSSProperties } from "react";

export const s = {
  box: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
  } satisfies CSSProperties,
  comingSoon: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  skeletonStack: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  summaryChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  summaryText: {
    fontSize: 13,
    lineHeight: 1.55,
    color: "var(--text-secondary)",
    margin: "0 0 14px",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  degradedText: {
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--warn, #b8860b)",
    margin: "0 0 14px",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  symbolList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  summaryTab: (active: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    border: "1px solid " + (active ? "var(--accent)" : "var(--border)"),
    borderRadius: 6,
    padding: "4px 10px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    background: active ? "var(--accent-bg)" : "transparent",
    color: active ? "var(--accent-text)" : "var(--text-secondary)",
  }),
  symbolRow: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    overflow: "hidden",
  } satisfies CSSProperties,
  symbolRowHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    background: "none",
    border: "none",
    padding: "10px 12px",
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  symbolRowChevron: (open: boolean): CSSProperties => ({
    color: "var(--text-muted)",
    flexShrink: 0,
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .12s",
  }),
  symbolRowName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  symbolRowCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  symbolRowDetail: {
    borderTop: "1px solid var(--border)",
    padding: 12,
  } satisfies CSSProperties,
  viewToggle: {
    display: "flex",
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  } satisfies CSSProperties,
  viewToggleBtn: (active: boolean): CSSProperties => ({
    border: "none",
    padding: "3px 10px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
  }),
  detail: {
    marginTop: 10,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    padding: 12,
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    padding: "4px 0",
  } satisfies CSSProperties,
  // Flex children default to min-width:auto (their content's intrinsic
  // width), so a long file path can push this item wider than the row and
  // overflow the card. minWidth:0 lets it shrink; overflowWrap wraps it
  // instead of clipping. callerName stays flexShrink:0 so the symbol name
  // on the right never gets squeezed out.
  callerFile: {
    minWidth: 0,
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  callerName: {
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  emptyCallers: {
    fontSize: 12.5,
    color: "var(--text-muted)",
    margin: 0,
  } satisfies CSSProperties,
  factsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 10,
    paddingTop: 10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  priorPrs: {
    marginTop: 16,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  priorPrsHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  priorPrsTitle: {
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  priorPrsCount: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    borderRadius: 10,
    padding: "1px 7px",
  } satisfies CSSProperties,
  priorPrsChevron: (open: boolean): CSSProperties => ({
    marginLeft: "auto",
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
    transition: "transform .12s",
  }),
  priorPrsList: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: 12,
  } satisfies CSSProperties,
  priorPrRow: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    padding: "10px 12px",
  } satisfies CSSProperties,
  priorPrHeader: {
    display: "flex",
    gap: 8,
    alignItems: "baseline",
    textDecoration: "none",
    color: "inherit",
    cursor: "pointer",
  } satisfies CSSProperties,
  priorPrNumber: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--accent-text, #e0a458)",
    flexShrink: 0,
  } satisfies CSSProperties,
  priorPrPrTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  priorPrMeta: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginTop: 3,
  } satisfies CSSProperties,
  priorPrNotes: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginTop: 6,
  } satisfies CSSProperties,
} as const;
