import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 900, display: "flex", flexDirection: "column", gap: 16 } satisfies CSSProperties,
  tileGrid: { display: "flex", gap: 16 } satisfies CSSProperties,
  tile: { flex: 1, minWidth: 0, display: "flex" } satisfies CSSProperties,
  /** ACCEPT RATE: the number and its ring share the tile's value slot. */
  gaugeValue: { display: "inline-flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  columns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, alignItems: "start" } satisfies CSSProperties,
  section: {
    padding: 18,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    minWidth: 0,
  } satisfies CSSProperties,
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
    marginBottom: 14,
  } satisfies CSSProperties,
  emptyNote: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    marginBottom: 8,
    fontSize: 13.5,
  } satisfies CSSProperties,
  agentAvatar: {
    display: "grid",
    placeItems: "center",
    width: 28,
    height: 28,
    borderRadius: 7,
    flexShrink: 0,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
  } satisfies CSSProperties,
  agentName: {
    flex: 1,
    minWidth: 0,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  agentOpen: { fontSize: 12.5, fontWeight: 600, color: "var(--accent-text)", flexShrink: 0 } satisfies CSSProperties,
} as const;
