import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 780 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 14, marginBottom: 16 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.45 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 14,
  } satisfies CSSProperties,
  searchIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  row: (dragOver: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "9px 10px",
    borderRadius: 7,
    background: "var(--bg-elevated)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: dragOver ? "var(--accent)" : "var(--border)",
  }),
  dragHandle: {
    display: "inline-flex",
    color: "var(--text-muted)",
    cursor: "grab",
    flexShrink: 0,
  } satisfies CSSProperties,
  reorderBtns: { display: "flex", flexDirection: "column", flexShrink: 0 } satisfies CSSProperties,
  reorderBtn: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--text-muted)",
    cursor: "pointer",
    display: "inline-flex",
  } satisfies CSSProperties,
  name: { fontSize: 13.5, fontWeight: 500, flex: 1 } satisfies CSSProperties,
  description: {
    fontSize: 12,
    color: "var(--text-muted)",
    flex: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
} as const;
