import type { CSSProperties } from "react";

export const s = {
  row: (highlight: boolean): CSSProperties => ({
    border: highlight ? "1px solid var(--crit)" : "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-surface)",
    minWidth: 0,
  }),
  button: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    minWidth: 0,
    boxSizing: "border-box",
    padding: "10px 12px",
    margin: 0,
    cursor: "pointer",
    fontSize: 13,
    lineHeight: 1.3,
    background: "transparent",
    border: "none",
    color: "inherit",
    textAlign: "left",
    fontFamily: "inherit",
  } satisfies CSSProperties,
  icon: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  iconHot: { color: "var(--crit)", flexShrink: 0 } satisfies CSSProperties,
  title: {
    fontWeight: 600,
    flex: "1 1 0",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  where: {
    fontSize: 12,
    color: "var(--accent-text)",
    flex: "0 1 auto",
    maxWidth: "46%",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  chevron: { color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  body: {
    margin: "0 12px 12px",
    padding: "10px 12px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
} as const;
