import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    minWidth: 0,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  title: { fontSize: 13, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  spacer: { marginLeft: "auto" } satisfies CSSProperties,
  quote: {
    margin: 0,
    padding: "2px 0 2px 12px",
    borderLeft: "3px solid var(--border-strong)",
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 12.5, color: "var(--text-muted)", margin: 0, lineHeight: 1.45 } satisfies CSSProperties,
  notice: {
    fontSize: 12.5,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "6px 10px",
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  scopeGrid: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)",
    gap: 20,
    minWidth: 0,
  } satisfies CSSProperties,
  label: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    margin: "0 0 8px",
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  labelIn: { color: "var(--ok)" } satisfies CSSProperties,
  labelOut: { color: "var(--text-muted)" } satisfies CSSProperties,
  list: {
    margin: 0,
    padding: 0,
    listStyle: "none",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  listItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    fontSize: 13,
    lineHeight: 1.45,
    color: "var(--text-secondary)",
    minWidth: 0,
  } satisfies CSSProperties,
  listItemText: { minWidth: 0, flex: 1 } satisfies CSSProperties,
  bullet: {
    width: 4,
    height: 4,
    borderRadius: "50%",
    background: "var(--text-muted)",
    flexShrink: 0,
    marginTop: 7,
  } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 6 } satisfies CSSProperties,
  risks: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  footer: {
    display: "flex",
    gap: 12,
    flexWrap: "wrap",
    fontSize: 12,
    color: "var(--text-muted)",
    borderTop: "1px solid var(--border)",
    paddingTop: 10,
  } satisfies CSSProperties,
  center: { display: "flex", flexDirection: "column", gap: 8, alignItems: "flex-start" } satisfies CSSProperties,
} as const;
