/**
 * Which commit a publication-branch commit should be built on.
 *
 * `commitFiles` used to parent unconditionally on the existing branch tip.
 * That is wrong for a long-lived generated branch: once its PR is merged into
 * base and the branch is NOT deleted, the branch stays forked from its old
 * pre-merge point forever. Every later export layers onto that stale fork, so
 * GitHub keeps computing the PR diff against a merge base that predates the
 * merge — the whole bundle renders as ADDED on every PR, even though base
 * already contains byte-identical files. (Observed: burnjohn/quick-blog#29,
 * 36k additions against a merge base with no `.devdigest/` at all, while
 * `main` had it.)
 *
 * So: when base carries commits the branch doesn't have, rebuild on base. The
 * branch's own generated content is not lost by that — it is fully
 * regenerated by this very commit, which is what makes resetting safe here and
 * would NOT be safe on a branch carrying hand-written work.
 */

export interface ParentChoiceInput {
  /** Tip of the target branch, or `null` when it does not exist yet. */
  branchSha: string | null;
  /** Tip of the base branch (e.g. `main`). */
  baseSha: string;
  /** Commits reachable from base but not from the branch — i.e. how far the
   *  branch has fallen behind. Ignored when the branch does not exist. */
  baseAheadBy: number;
}

export interface ParentChoice {
  parentSha: string;
  /** True when the branch is being re-pointed at base rather than extended.
   *  The caller must force-update the ref for this (the new commit is not a
   *  descendant of the old tip) — and it is worth logging. */
  rebasedOntoBase: boolean;
}

export function chooseCommitParent(input: ParentChoiceInput): ParentChoice {
  if (input.branchSha === null) {
    return { parentSha: input.baseSha, rebasedOntoBase: false };
  }
  if (input.baseAheadBy > 0) {
    return { parentSha: input.baseSha, rebasedOntoBase: true };
  }
  return { parentSha: input.branchSha, rebasedOntoBase: false };
}
